name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]

env:
  TEST_TAG: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:test
  LATEST_TAG: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

jobs:
  docker:
    runs-on: unbuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Export to Docker
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test Image
        run: |
          docker run --rm ${{ env.TEST_TAG }}  

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.LATEST_TAG }}
